---
# This workflow is centrally managed in https://github.com/LizardByte/.github/
# Don't make changes to this file in this repo as they will be overwritten with changes made to the same file in
# the above-mentioned repo.

name: common lint
permissions: {}

on:
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    name: Common Lint
    uses: LizardByte/.github/.github/workflows/__call-common-lint.yml@4e4aa17193e825a20773bb38157b86186129d579  # master
    if: ${{ github.repository != 'LizardByte/.github' }}
    permissions:
      contents: read
      pull-requests: read
